### ISSUE TITLE
Bug: Test various custom skills and ensure they work

### ISSUE THREAD

**Issue by XxX-Daniil-underscore-Zaikin-XxX** [XxX-Daniil-underscore-Zaikin-XxX/CustomSkillsMenu#20]
- [x] Ascension
- [x] SoS 2
- [x] Stormcrown
- [x] Pilgrim
- [x] Tales of the Berserky

**Comment by XxX-Daniil-underscore-Zaikin-XxX** [comment]
Looks like I've found the issue. CSFv2 changed the functionality from global vars to using the skill ID (gotten from the file).

CSFv3 reverted to showMenu because it suited the multi-tree menus better. The solution would then be to check for CSFv2 and proceed accordingly.

**Comment by XxX-Daniil-underscore-Zaikin-XxX** [comment]
Tales of Berserky(r) is CSFv3. It was appearing properly on the user's menu, it was just called something different.

**Comment by XxX-Daniil-underscore-Zaikin-XxX** [comment]
Pilgrim has no custom skills (lol)

**Comment by XxX-Daniil-underscore-Zaikin-XxX** [comment]
Stormcrown didn't use showMenu, so I fixed this in the relevant PR.

**Comment by FardeenRiyadh16** [comment]
Berserker worked for me since initial release also here's Pilgrim CSF:
https://www.nexusmods.com/skyrimspecialedition/mods/93913

**Comment by XxX-Daniil-underscore-Zaikin-XxX** [comment]
> Berserker worked for me since initial release also here's Pilgrim CSF: https://www.nexusmods.com/skyrimspecialedition/mods/93913

Thanks for the info and the testing! I checked that mod out, and it works on my end. Looks like this patch will fix em.
